# Generated by Django 3.1.2 on 2020-10-25 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('repo', models.CharField(max_length=200, null=True)),
                ('file_path', models.CharField(max_length=200, null=True)),
                ('line', models.SmallIntegerField(null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.repository')),
            ],
        ),
    ]
